### ISSUE TITLE
handle error on startup

### ISSUE THREAD

**Issue by dmd** [jabyrd3/typeto.me2#6]
```
$ bin/type
Listening on http://localhost:8089/
e NotFound: No such file or directory (os error 2): readfile './rooms.json'
    at Object.readFileSync (ext:deno_fs/30_fs.js:757:10)
    at new Rooms (file:///app/index.ts:134:25)
    at file:///app/index.ts:200:15 {
  name: "NotFound",
  code: "ENOENT"
}
Listening on http://localhost:8090/
```

I assume that's benign, but if so, should be handled.

**Comment by jabyrd3** [comment]
yeah, it's wrapped in a try/catch block already on l129 of server/index.ts, i was just logging the error for dev. will trim the error so it looks less spooky

**Comment by jabyrd3** [comment]
commit 3329 fixes
